webapp/account/views.py
"""Реализация разделов сайта для работы с аккаунтами Steam."""
import os

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from webapp.account.forms import SteamLoginForm
from webapp.account.utils import auth_attempt, load_inventory_contents, \
    update_acc_info, update_inventory_contents
from webapp.db import db
from webapp.user.models import User

blueprint = Blueprint('account', __name__,
                      url_prefix='/accounts')


@blueprint.route('/make_session', methods=['GET', 'POST'])
@login_required
def make_session():
    """Подключение для пользователя нового аккаунта Steam."""
    title = 'Подключение аккаунта Steam'
    form = SteamLoginForm()
    user = User.query.filter_by(username=current_user.username).first()
    accounts = user.accounts.all()

    # Если есть атрибут login - вставляем его в поле username шаблона
    login = request.args.get('login')
    if login is None:
        login = ''

    auth_code = None
    two_factor_code = None

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        if form.auth_code.data:
            auth_code = form.auth_code.data
        if form.two_factor_code.data:
            two_factor_code = form.two_factor_code.data
        user_id = user.user_id

        try_login = auth_attempt(
            user_id=user_id,
            username=username,
            password=password,
            auth_code=auth_code,
            two_factor_code=two_factor_code,
        )
        if try_login:
            # Обновляем сессию пользователя после коммита
            user = User.query.filter_by(user_id=user_id).first()
            if type(try_login) == str:
                return redirect(try_login)
            else:
                return redirect(url_for(
                    'user.profile',
                    username=user.username,
                ))
        else:
            flash('Неудачная попытка авторизации', 'warning')

    template_path = os.path.join('account', 'make_session.html')
    return render_template(
        template_path,
        title=title,
        login=login,
        form=form,
        user=user,
        accounts=accounts,
    )


@blueprint.route('/<steam_login>')
@login_required
def account(steam_login):
    """Информация о подключенном аккаунте Steam."""
    title = f'Аккаунт {steam_login}'
    user = User.query.filter_by(username=current_user.username).first()
    db_steam_acc = user.accounts.filter_by(username=steam_login).first()

    if db_steam_acc:
        items = load_inventory_contents(db_steam_acc)
        update_acc_info(db_steam_acc)
        update_inventory_contents(db_steam_acc)
    else:
        items = None

    user = User.query.filter_by(username=current_user.username).first()
    template_path = os.path.join('account', 'account.html')
    return render_template(
        template_path,
        title=title,
        user=user,
        account=db_steam_acc,
        items=items,
    )


@blueprint.route('/<steam_login>/trade_history')
@login_required
def trade_history(steam_login):
    """Информация об истории торговли подключенного аккаунта Steam."""
    title = f'История торговли {steam_login}'
    template_path = os.path.join('account', 'trade_history.html')
    return render_template(
        template_path,
        title=title,
    )


@blueprint.route('/delete/<steam_login>')
@login_required
def remove_account(steam_login):
    """Отключение аккаунта Steam и удаление записи из БД."""
    user = User.query.filter_by(username=current_user.username).first()
    accounts = user.accounts.all()
    fetch_account = user.accounts.filter_by(
        username=steam_login).first_or_404()
    db.session.delete(fetch_account)
    db.session.commit()
    flash(f'Аккаунт {steam_login} отключен.', 'danger')
    template_path = os.path.join('user', 'profile.html')
    return render_template(
        template_path,
        user=user,
        accounts=accounts,
    )

webapp/user/views.py
"""Реализация разделов сайта для работы с пользователями."""
import os

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

from webapp.account.models import Account
from webapp.account.schemas import AccountSchema
from webapp.db import db
from webapp.item.schemas import DescriptionSchema, ItemSchema
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.user.schemas import UserSchema

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Авторизация пользователя."""
    title = 'Авторизация'
    if current_user.is_authenticated:
        return redirect(url_for(
            'user.profile',
            username=current_user.username,
        ))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(User).filter_by(
            username=form.username.data,
        ).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password', 'danger')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('user.profile',
                                username=form.username.data)
        return redirect(next_page)
    template_path = os.path.join('user', 'login.html')
    return render_template(
        template_path,
        title=title,
        form=form,
    )


@blueprint.route('/logout')
def logout():
    """Выход из учетной записи."""
    logout_user()
    return redirect(url_for('user.login'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    """Регистрация нового пользователя."""
    title = 'Регистрация'
    if current_user.is_authenticated:
        return redirect(url_for('user.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('You are now a registered user!', 'success')
        return redirect(url_for('user.login'))
    template_path = os.path.join('user', 'register.html')
    return render_template(
        template_path,
        title=title,
        form=form,
    )


@blueprint.route('/<username>')
@login_required
def profile(username):
    """Профиль зарегистрированного пользователя."""
    user = db.session.query(User).filter_by(username=username).first_or_404()
    accounts = user.accounts.all()
    template_path = os.path.join('user', 'profile.html')
    return render_template(
        template_path,
        user=user,
        accounts=accounts,
    )

webapp/templates/base/menu.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#171a21;color: #8F98A0!important;">
    <div class="container-fluid">
        <a class="navbar-brand">Steam Inventory Analyst</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar" style="background-color:#171a21;color: #8F98A0!important;">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if current_user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.profile', username=current_user.username) }}">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

webapp/templates/base/page.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <!-- My CSS styles -->
        <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
        <!-- Popper and Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
        <!-- Chart.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js" integrity="sha512-hZf9Qhp3rlDJBvAKvmiG+goaaKRZA6LKUO35oK6EsM0/kjPK32Yw7URqrq3Q+Nvbbt8Usss+IekL7CRn83dYmw==" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
        {% if title %}
        <title>{{ title }} - Steam Inventory Analyst</title>
        {% else %}
        <title>Steam Inventory Analyst</title>
        {% endif %}
    </head>
    <body>
        {% include "base/menu.html" %}
        {% with messages = get_flashed_messages(with_categories=True, category_filter=['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark']) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="container-fluid py-4 px-4">
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            <div class="d-inline-flex px-2">{{ message }}</div>
                            {% if category == 'light' %}
                            {% set account = request.path.split('/accounts/')[1] %}
                            <a role="button" class="btn btn-primary btn-sm d-inline-flex" href="{{ url_for('account.make_session', login=account) }}">Восстановить</a>
                            {% endif %}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

webapp/templates/base/scripts.html
<script>
function openUrl(link) {
    location.href = link;
}
</script>

webapp/templates/base/styles.html
<style>
body {
    background-color: #1b2838;
    color: #8F98A0;
}
#main_body {
    background-color: #171a21;
    width: 80%;
    margin: 20px auto ;
}
tr.collapse {
    cursor: pointer;
}
.accordion-button{
    position:relative;
    display:flex;
    align-items:center;
    width:100%;
    padding:0.5rem 0.5rem;
    font-size:1rem;
    color:#8F98A0;
    text-align:left;
    background-color: transparent;
    border:0;
    border-radius:0;
    overflow-anchor:none;
    transition:color .15s ease-in-out,background-color .15s ease-in-out,border-color 0s ease-in-out,box-shadow 0s ease-in-out,border-radius 0s ease
}
@media (prefers-reduced-motion:reduce){
    .accordion-button{
        transition:none
    }
}
.accordion-button:not(.collapsed){
    color: #8F98A0;
    background-color: transparent;
    box-shadow: none;
}
.accordion-button:not(.collapsed)::after{
    background-image:url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%238F98A0'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
    transform:rotate(180deg)
}
.accordion-button::after{
    flex-shrink:0;
    width:1.25rem;
    height:1.25rem;
    margin-left:auto;
    content:"";
    fill: #46602a;
    background-image:url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%238F98A0'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
    background-repeat:no-repeat;
    background-size:1.25rem;
    transition:transform .2s ease-in-out}
@media (prefers-reduced-motion:reduce){
    .accordion-button::after{transition:none}
}
.accordion-button:hover{
    z-index:2
}
.accordion-button:focus{
    z-index:3;
    outline:0;
}
</style>