webapp/item/models.py
"""Модель таблиц связанных с отображением предметов сообщества Steam."""
from sqlalchemy.orm import relationship

from webapp.db import db


class Item(db.Model):
    """Модель таблицы предметов в инвентаре Steam.

    Хранит идентификационный номер предмета в базе, идентификационный номер
    предмета на серверах Steam, идентификационный номер описания предмета,
    идентификационные номер аккаунта-владельца предмета.
    """

    __tablename__ = "items"

    item_id = db.Column(db.Integer, primary_key=True)
    asset_id = db.Column(db.BigInteger, index=True)
    class_id = db.Column(db.Integer, db.ForeignKey('descriptions.class_id'))
    account_id = db.Column(db.Integer, db.ForeignKey('accounts.account_id'))
    descriptions = relationship("Description", backref='items', lazy="joined")

    def __repr__(self):
        """Определяем формат вывода объекта класса Item."""
        return f"Item # {self.asset_id}."


class Description(db.Model):
    """Модель таблицы описаний предметов сообщества Steam.

    Хранит идентификационный номер описания, идентификационный номер
    приложения, идентификатор иконки предмета, имя предмета на торговой
    площадке, имя предмета для вывода, тип предмета, описание предмета,
    список тегов: редкость, игра, тип предмета, тип коллекционной карточки.
    """

    __tablename__ = "descriptions"

    class_id = db.Column(db.Integer, primary_key=True)
    app_id = db.Column(db.SmallInteger)
    icon_url_large = db.Column(db.String)
    market_hash_name = db.Column(db.String)
    market_name = db.Column(db.String)
    item_type = db.Column(db.String)
    value = db.Column(db.String)
    rarity_tag = db.Column(db.String)
    game_tag = db.Column(db.String)
    item_type_tag = db.Column(db.String)
    card_border_tag = db.Column(db.String)

    def __repr__(self):
        """Определяем формат вывода объекта класса Description."""
        return f"Description for {self.market_hash_name}."

webapp/item/views.py
"""Реализация разделов сайта для работы с предметами сообщества Steam."""
import os

from flask import Blueprint, render_template
from flask_login import current_user, login_required

from webapp.account.models import Account

blueprint = Blueprint('item', __name__,
                      url_prefix='/items')


@blueprint.route('/<steam_login>/items/<item_id>')
@login_required
def item_description(steam_login, item_id):
    """Описание предмета из коллекции Steam."""
    title = 'title'
    account = Account.query.filter_by(
        username=steam_login, user_id=current_user.user_id).first()
    item = account.items.filter_by(asset_id=item_id).first()
    description = item.descriptions
    template_path = os.path.join('item', 'item.html')
    return render_template(template_path, title=title, account=account,
                           description=description,
                           )

webapp/templates/item/inventory.html
<div class="d-flex flex-column  align-items-center justify-content-top my-1 mx-1">
  <h4 class=""><b>Инвентарь</b></h4>
  <table class="table table-dark table-striped table-hover">
            <thead>
              <tr class="">
                  <th>Иконка</th>
                  <th>Наименование</th>
                  <th>Тип предмета</th>
                  <th>Редкость</th>
                  <th>Игра</th>
              </tr>
            </thead>
            <tbody class="">
              {% if items %}
                {% for item, value in items.items()|sort(reverse=false, attribute="1.class_id") %}
                  <tr class="" onclick="openUrl(document.getElementById('{{ item }}').getAttribute('data-href'))" data-href="{{ url_for('item.item_description', steam_login=account.username, item_id=item) }}" id="{{ item }}">
                      <td><img src="https://community.akamai.steamstatic.com/economy/image/{{ items[item]['icon_url_large'] }}/32fx32f" alt="item icon"></td>
                      <td>{{ items[item]['market_name'] }}</td>
                      <td>{{ items[item]['item_type'] }}</td>
                      <td>{{ items[item]['rarity_tag'] }}</td>
                      <td>{{ items[item]['game_tag'] }}</td>
                  </tr>
                {% endfor %}
              {% else %}
              <tr><td colspan="5">Инвентарь пуст</td></tr>
              {% endif %}
            </tbody>
  </table>
</div>

webapp/templates/item/item.html
{% extends "base/page.html" %}
{% block content %}
    {% include "account/info.html" %}
    <div class="my-2" id="main_body">
        <div class="d-flex align-items-center justify-content-center py-3 p-1">
            {% if description %}
            <div><img src="https://community.akamai.steamstatic.com/economy/image/{{ description.icon_url_large }}/" alt="item icon"><br></div>
            <div class=""><h1>{{ description.market_name }}</h1><br>{{ description.value }}</div>
            {% endif %}
        </div>
    </div>
<script>
   var Canvas1 = document.getElementById("chart1").getContext("2d");
   var Canvas2 = document.getElementById("chart2").getContext("2d");
   var speedData = {
  labels: ["0s", "10s", "20s", "30s", "40s", "50s", "60s"],
  datasets: [{
    label: "Something",
    data: [0, 59, 75, 20, 20, 55, 40],
  }]
};
var chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    legend: {
        display: true,
        position: 'top',
        labels: {
            boxWidth: 80,
            fontColor: 'black'
        }
    }
};
var lineChart1 = new Chart(Canvas1, {
    type: 'line',
    data: speedData,
    options: chartOptions
});
var lineChart2 = new Chart(Canvas2, {
    type: 'line',
    data: speedData,
    options: chartOptions
});
</script>
{% endblock %}